---
title: "Model evaluation VI"
author: "Koen Hufkens"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Model evaluation VI}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidymodels)
library(xgboost)
library(ranger)
library(caret)
library(reactable)
library(readr)
library(forcats)
source(here::here("R/calc_VI.R"))
source(here::here("R/index_flue.R"))
set.seed(0)

# read in training data
ml_df <- readRDS(
  here::here("data/machine_learning_training_data.rds")
  ) |>
  na.omit()

vi <- calc_VI(ml_df, indices = here::here("data/spectral-indices-table.csv"))
ml_df <- bind_cols(ml_df, vi)

# create a data split across
# across both droughted and non-droughted days
ml_df_split <- ml_df |>
  rsample::initial_split(
    strata = is_flue_drought,
    prop = 0.8
  )

# select training and testing
# data based on this split
train <- rsample::training(ml_df_split) |>
  select(-is_flue_drought)
test <- rsample::testing(ml_df_split) |>
  select(-is_flue_drought)

# read in precompiled model
regression_model <- readRDS(
  here::here("data/regression_model_spatial.rds")
  )

# run the model on our test data
# using predict()
test_results <- predict(
  regression_model,
  test)$.pred

df <- data.frame(
  test,
  flue_predicted = test_results
  )

```

Comparing VI versus fLUE

```{r echo = FALSE, message=FALSE, warning=FALSE}

df <- df |>
  select(
    -starts_with("Nadir"),
    -starts_with("LST")
  )

df_long <- df |>
  pivot_longer(
    cols = 7:ncol(df),
    names_to = "index",
    values_to = "value"
  ) |>
  filter(
    !is.na(value),
    !is.infinite(value)
  )

rsq <- df_long |>
  group_by(cluster, index, site) |>
  do({
  
    rsq <- summary(lm(flue ~ value, data = .))$r.squared
    
    data.frame(rsq)
    
  }) |>
  mutate(
    flue = ifelse(index == "flue_predicted", TRUE, FALSE)
  )

```


```{r echo = FALSE, message=FALSE, warning=FALSE}

# plot all validation graphs
p <- ggplot(rsq) +
  geom_boxplot(
    aes(
      cluster,
      rsq,
      fill = flue
    )
  ) +
  theme_classic()

print(p)
```

Which one performs best?
```{r}
best_ind <- rsq |> 
  filter(cluster != "cNA") |> 
  group_by(index) |> 
  summarise(rsq = median(rsq)) |> 
  arrange(desc(rsq)) |> 
  dplyr::slice(1:10) |> 
  pull(index)

rsq |> 
  filter(index %in% best_ind, cluster != "cNA") |> 
  mutate(index = fct_reorder(index, rsq, .fun = "mean")) |> 
  ggplot() +
  geom_boxplot(
    aes(
      reorder(index, desc(rsq)),
      rsq
    ),
    fill = "grey"
  ) +
  facet_wrap(~cluster, nrow = 3) +
  theme_classic()
```

```{r}
rank_vi <- rsq |>
  ungroup() |>
  group_by(cluster) |>
  mutate(
    rsq_flue = quantile(rsq[index == "flue_predicted"], 0.5)
  ) |>
  filter(
    !flue,
    rsq > rsq_flue
  ) |>
  select(
    index,
    rsq
  ) |>
  group_by(cluster, index) |>
  summarize(
    rsq = mean(rsq)
  )


reactable::reactable(rank_vi)

```
